pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t wthduaa/diabetes-predictor:latest docker/'
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-cred', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    bat 'echo %DOCKER_PASSWORD%> temp.txt'
                    bat 'type temp.txt | docker login -u %DOCKER_USERNAME% --password-stdin'
                    bat 'del temp.txt'
                    bat 'docker push wthduaa/diabetes-predictor:latest'
                }
            }
        }
        
        stage('Email Notification') {
            steps {
                bat '''
                echo "CI/CD Pipeline Completed Successfully!" | mail -s "Jenkins Pipeline Success" fatimaduaa053@gmail.com
                '''
            }
        }
    }
}
