name: Feature Testing

on:
  pull_request:
    branches:
      - test  # Runs when a PR is made to test

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Debug Installed Packages
        run: |
          python -c "import sklearn; print('Scikit-learn:', sklearn.__version__)"
          python -c "import numpy; print('Numpy:', numpy.__version__)"
          python -c "import joblib; print('Joblib:', joblib.__version__)"

      - name: Run Unit Tests
        run: pytest tests/
